language: python

python:
  - 3.6

services:
  - docker

install:
  # Adds dependencies:
  - pip install docker-image-size-limit
  # Building image itself:
  - docker build -t caddy-gen:latest .
  - docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name caddy-gen caddy-gen

script:
  - sleep 5
  - docker ps | grep -q caddy-gen # there should be a docker process
  - curl 127.0.0.1:80 # it should be available and return 404
  - disl caddy-gen:latest 90MB

notifications:
  email:
    on_success: never
    on_failure: change
