version: "3.8"
services:
  caddy-gen:
    container_name: caddy2-gen
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./caddy-info:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoami
      - whoami2
    labels:
      - "virtual.host=static-1.localhost static-2.localhost"
      - "virtual.static.root=/usr/share/caddy/"
      - "virtual.noProxy=true"

  whoami:
    image: "katacoda/docker-http-server:v1"
    labels:
      - "virtual.host=test1.localhost"

  whoami2:
    image: "katacoda/docker-http-server:v2"
    labels:
      - "virtual.host=myapp.com" # your domain
      - "virtual.alias=www.myapp.com" # alias for your domain (optional)
      - "virtual.port=80" # exposed port of this container
      - "virtual.tls-email=admin@myapp.com" # ssl is now on
